const Ingredients = [ {
checked : false, 
amount: '1 1/2 cups', 
ingredient: 'milk' }, 
{ checked: false,
amount:'1/2 cup',
ingredient: 'mascarpone' },
{ checked: false,
    amount: '1/2 tsp',
    ingredient: 'pink salt' },
{ checked: false, amount: '1 lb ',
ingredient: 'Black Mission Figs' },
{ checked: false,
    amount: '1/2 cup',
    ingredient: 'brown sugar' },
{ checked: false,
    amount: '2-4 tbsp', ingredient: 'water' },
{ checked: false, 
   amount: '1 1/2 cups', ingredient:'heavy cream' },
{ checked: false, 
    amount: '1/3 cup', ingredient: 'granulated sugar' },
{ checked: false,
    amount:'2',
    ingredient: 'egg yolks' },
{ checked: false,
    amount:'1 ', ingredient: 'lemon, juiced' },
{ checked: false,
    amount: '2 ', ingredient: 'tbsp butter' },
{ checked: false,
    amount: '1 cup ', ingredient:'honey roasted pecans, roughly chopped' }]

export default Ingredients;